// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbbqdntjqhpiautrwmsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhiYnFkbnRqcWhwaWF1dHJ3bXNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0OTg4ODEsImV4cCI6MjA2NDA3NDg4MX0.PVxs7MnOOw8kg8U0o5rfOtpFYip3I-wACdraIg1Vx1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);